image: privacybydesign/golang_sql:latest

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - vendor/go/pkg/mod/

stages:
  - test
  - build

variables:
  GOFLAGS: -mod=readonly
  GOPATH: ${CI_PROJECT_DIR}/vendor/go
  PACKAGE_NAME: github.com/privacybydesign/irmago
  PLATFORMS: linux/amd64 darwin/amd64 darwin/arm64 windows/amd64 linux/arm linux/arm64

before_script:
  - set -euxo pipefail
  - service mysql start
  - mysql -e "create database test"
  - mysql -e "grant all privileges on *.* to 'testuser'@'localhost' identified by 'testpassword'"
  - mysql -e "flush privileges"

unit_tests:
  stage: test
  script:
  - go test -tags=local_tests -p 1 ./...

binaries:
  stage: build
  artifacts:
    # Disabling artifact expiry is not supported yet, so make
    expire_in: 100 year
    paths:
      - artifacts/*
  script:
    - mkdir -p artifacts
    - for PLATFORM in $PLATFORMS; do
        export GOOS=${PLATFORM%/*};
        export GOARCH=${PLATFORM#*/};
        export CGO_ENABLED=0;
        export GOARM=6;

        OUTPUT_NAME="irma-${CI_COMMIT_REF_SLUG}-${GOOS}-${GOARCH}";
        if [[ "$GOOS" == "windows" ]]; then
          OUTPUT_NAME="${OUTPUT_NAME}.exe";
        fi;

        go build -a -ldflags '-extldflags "-static"' -o "artifacts/$OUTPUT_NAME" ./irma;
      done;

